# Generated by Django 4.1.7 on 2023-03-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_picker', '0003_rename_realease_date_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.TextField(),
        ),
    ]
