# Generated by Django 4.1.7 on 2023-03-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('overview', models.TextField()),
                ('realease_date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('image', models.TextField()),
            ],
        ),
    ]
